// Generates responsive AVIF/WebP/JPEG derivatives from assets/photos/*.jpg into
// public/photos/, plus a typed manifest at src/lib/photos.ts.
//
//   npm run photos
//
// Originals stay out of public/ so only optimized bytes ever ship. Re-run after
// adding or replacing a source photo.
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SRC = "assets/photos";
const OUT = "public/photos";
const MANIFEST = "src/lib/photos.ts";

const WIDTHS = [480, 768, 1080, 1440];
const FORMATS = [
  { ext: "avif", options: { quality: 52, effort: 6 } },
  { ext: "webp", options: { quality: 74, effort: 5 } },
  { ext: "jpg", options: { quality: 80, mozjpeg: true, progressive: true } },
];

/** Human-readable alt text and CSS object-position, keyed by file slug. */
const META = {
  "blue-standing": {
    alt: "Brandon Price-Crum in a royal blue pinstripe suit, buttoning his jacket",
    position: "50% 22%",
  },
  "desk-seated": {
    alt: "Brandon Price-Crum seated at his desk, hands clasped, framed by his Top 40 Under 40 award and a statue of Lady Justice",
    position: "50% 40%",
  },
  "desk-standing": {
    alt: "Brandon Price-Crum standing at his office desk beneath his Alabama State University and FAMU College of Law diplomas",
    position: "50% 40%",
  },
  "gray-chin": {
    alt: "Brandon Price-Crum in a gray suit, hand to his chin, smiling",
    position: "50% 18%",
  },
  "gray-leaning": {
    alt: "Brandon Price-Crum in a gray suit leaning against a reclaimed wood beam",
    position: "50% 20%",
  },
  "gray-seated": {
    alt: "Brandon Price-Crum in a gray suit seated on a stool",
    position: "50% 25%",
  },
  "navy-headshot": {
    alt: "Portrait of Brandon Price-Crum in a navy suit and striped tie",
    position: "50% 25%",
  },
  "navy-seated-serious": {
    alt: "Brandon Price-Crum in a navy suit seated on a stool",
    position: "50% 25%",
  },
  "navy-seated-smiling": {
    alt: "Brandon Price-Crum in a navy suit seated on a stool, smiling",
    position: "50% 25%",
  },
};

const srcSetFor = (slug, ext, widths) =>
  widths.map((w) => `/photos/${slug}-${w}.${ext} ${w}w`).join(", ");

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f)).sort();
  if (files.length === 0) throw new Error(`No source images found in ${SRC}/`);

  const entries = [];

  for (const file of files) {
    const slug = path.basename(file, path.extname(file));
    const input = path.join(SRC, file);
    const image = sharp(input, { failOn: "error" }).rotate();
    const { width, height } = await image.metadata();
    if (!width || !height) throw new Error(`Could not read dimensions for ${file}`);

    // Never upscale: cap the ladder at the source width, always keeping one rung.
    const widths = WIDTHS.filter((w) => w <= width);
    if (widths.length === 0 || widths.at(-1) !== Math.min(width, WIDTHS.at(-1))) {
      widths.push(Math.min(width, WIDTHS.at(-1)));
    }
    const ladder = [...new Set(widths)].sort((a, b) => a - b);

    for (const w of ladder) {
      const resized = sharp(input).rotate().resize({ width: w, withoutEnlargement: true });
      await Promise.all(
        FORMATS.map(({ ext, options }) =>
          resized
            .clone()
            [ext === "jpg" ? "jpeg" : ext](options)
            .toFile(path.join(OUT, `${slug}-${w}.${ext}`)),
        ),
      );
    }

    // 20px blurred base64 stand-in so slots paint instantly instead of flashing gray.
    const placeholder = await sharp(input)
      .rotate()
      .resize({ width: 20 })
      .blur(1.4)
      .webp({ quality: 28 })
      .toBuffer();

    const meta = META[slug];
    if (!meta) throw new Error(`Missing META entry for "${slug}" in scripts/build-photos.mjs`);

    entries.push({
      slug,
      width,
      height,
      alt: meta.alt,
      position: meta.position,
      src: `/photos/${slug}-${ladder.at(-1)}.jpg`,
      avif: srcSetFor(slug, "avif", ladder),
      webp: srcSetFor(slug, "webp", ladder),
      jpg: srcSetFor(slug, "jpg", ladder),
      placeholder: `data:image/webp;base64,${placeholder.toString("base64")}`,
    });
  }

  const body = entries
    .map(
      (e) => `  "${e.slug}": {
    width: ${e.width},
    height: ${e.height},
    alt: ${JSON.stringify(e.alt)},
    position: ${JSON.stringify(e.position)},
    src: ${JSON.stringify(e.src)},
    avif: ${JSON.stringify(e.avif)},
    webp: ${JSON.stringify(e.webp)},
    jpg: ${JSON.stringify(e.jpg)},
    placeholder: ${JSON.stringify(e.placeholder)},
  },`,
    )
    .join("\n");

  const out = `// AUTO-GENERATED by scripts/build-photos.mjs — do not edit by hand.
// Run \`npm run photos\` after changing anything in assets/photos/.

export type Photo = {
  width: number;
  height: number;
  alt: string;
  /** CSS object-position that keeps his face in frame under any crop. */
  position: string;
  src: string;
  avif: string;
  webp: string;
  jpg: string;
  placeholder: string;
};

export const photos = {
${body}
} satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;
`;

  await writeFile(MANIFEST, out);

  const total = entries.length * FORMATS.length;
  console.log(`✓ ${entries.length} photos → ${OUT}/ (${total}+ files), manifest → ${MANIFEST}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
